# 工作流名称
name: Release_ADblock_file

# 触发条件
on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  create-release:
    runs-on: ubuntu-latest  # 在最新版本的 Ubuntu 上运行
    steps:
      # 步骤1：检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 步骤2：获取当前时间并设置时间戳
      - name: Get current time
        id: current-time
        run: echo "time=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV  # 将时间保存为环境变量

      # 步骤3：创建新的发布
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 使用存储在仓库密钥中的 TOKEN 进行身份验证
        with:
          tag_name: release-${{ env.time }}  # 使用时间戳作为标签名，确保唯一性
          release_name: Release ${{ env.time }}  # 使用时间戳作为发布名称
          body: "Automated periodic release of adblock files."  # 发布说明
          draft: false  # 创建正式发布，而非草稿
          prerelease: false  # 不是预发布

      # 步骤4：上传 adblock_reject_surge_ruleset.list 文件
      - name: Upload adblock_reject_surge_ruleset.list
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 使用 TOKEN 进行身份验证
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # 使用创建发布时生成的URL
          asset_path: ./adblock_reject_surge_ruleset.list
          asset_name: adblock_reject_surge_ruleset.list
          asset_content_type: text/plain


      # 步骤5：上传 adblock_reject_surge_module.sgmodule 文件
      - name: Upload adblock_reject_surge_module.sgmodule
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 使用 TOKEN 进行身份验证
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./adblock_reject_surge_module.sgmodule
          asset_name: adblock_reject_surge_module.sgmodule
          asset_content_type: text/plain
