name: Trigger in sequence

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟触发一次

jobs:
  trigger_adblock_rule_generator_ruleset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger and verify Run_AdBlock_Rule_Generator_RULESET
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          workflow_id="Run_AdBlock_Rule_Generator_RULESET.yml"
          ref="main"
          url="https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Surge/actions/workflows/$workflow_id/dispatches"
          
          echo "Triggering workflow at $url"

          response=$(curl -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "$url" \
            -d "{\"ref\":\"$ref\"}")
          echo "Triggered workflow $workflow_id: $response"

          # 验证工作流成功触发
          while : ; do
            status=$(curl -s -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Surge/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
              | jq -r '.workflow_runs[0].conclusion')

            if [[ "$status" == "success" ]]; then
              echo "Workflow $workflow_id completed successfully."
              break
            elif [[ "$status" == "failure" ]]; then
              echo "Workflow $workflow_id failed."
              exit 1
            else
              echo "Waiting for workflow $workflow_id to complete..."
              sleep 30
            fi
          done

          # 等待90秒
          sleep 90

  trigger_rename_and_push_file:
    runs-on: ubuntu-latest
    needs: trigger_adblock_rule_generator_ruleset  # 保证在前一个工作流成功后触发
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger and verify Rename_and_Push_File
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          workflow_id="Rename_and_Push_File.yml"
          ref="main"
          url="https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Surge/actions/workflows/$workflow_id/dispatches"
          
          echo "Triggering workflow at $url"

          response=$(curl -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "$url" \
            -d "{\"ref\":\"$ref\"}")
          echo "Triggered workflow $workflow_id: $response"

          # 验证工作流成功触发
          while : ; do
            status=$(curl -s -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Surge/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
              | jq -r '.workflow_runs[0].conclusion')

            if [[ "$status" == "success" ]]; then
              echo "Workflow $workflow_id completed successfully."
              break
            elif [[ "$status" == "failure" ]]; then
              echo "Workflow $workflow_id failed."
              exit 1
            else
              echo "Waiting for workflow $workflow_id to complete..."
              sleep 30
            fi
          done

          # 等待90秒
          sleep 90

  trigger_release_adblock_file:
    runs-on: ubuntu-latest
    needs: trigger_rename_and_push_file  # 保证在前一个工作流成功后触发
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger and verify Release_ADblock_file
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          workflow_id="Release_ADblock_file.yml"
          ref="main"
          url="https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Surge/actions/workflows/$workflow_id/dispatches"
          
          echo "Triggering workflow at $url"

          response=$(curl -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "$url" \
            -d "{\"ref\":\"$ref\"}")
          echo "Triggered workflow $workflow_id: $response"

          # 验证工作流成功触发
          while : ; do
            status=$(curl -s -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Surge/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
              | jq -r '.workflow_runs[0].conclusion')

            if [[ "$status" == "success" ]]; then
              echo "Workflow $workflow_id completed successfully."
              break
            elif [[ "$status" == "failure" ]]; then
              echo "Workflow $workflow_id failed."
              exit 1
            else
              echo "Waiting for workflow $workflow_id to complete..."
              sleep 30
            fi
          done
